// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DetachOrDeleteVolumeRequest struct {
	// A Nomad ACL token.
	XNomadToken *string `header:"style=simple,explode=false,name=X-Nomad-Token"`
	// The action to perform on the Volume (create, detach, delete).
	Action string `pathParam:"style=simple,explode=false,name=action"`
	// Can be used to ensure operations are only run once.
	IdempotencyToken *string `queryParam:"style=form,explode=true,name=idempotency_token"`
	// Filters results based on the specified namespace.
	Namespace *string `queryParam:"style=form,explode=true,name=namespace"`
	// Specifies node to target volume operation for.
	Node *string `queryParam:"style=form,explode=true,name=node"`
	// Filters results based on the specified region.
	Region *string `queryParam:"style=form,explode=true,name=region"`
	// Volume unique identifier.
	VolumeID string `pathParam:"style=simple,explode=false,name=volumeId"`
}

func (o *DetachOrDeleteVolumeRequest) GetXNomadToken() *string {
	if o == nil {
		return nil
	}
	return o.XNomadToken
}

func (o *DetachOrDeleteVolumeRequest) GetAction() string {
	if o == nil {
		return ""
	}
	return o.Action
}

func (o *DetachOrDeleteVolumeRequest) GetIdempotencyToken() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyToken
}

func (o *DetachOrDeleteVolumeRequest) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *DetachOrDeleteVolumeRequest) GetNode() *string {
	if o == nil {
		return nil
	}
	return o.Node
}

func (o *DetachOrDeleteVolumeRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *DetachOrDeleteVolumeRequest) GetVolumeID() string {
	if o == nil {
		return ""
	}
	return o.VolumeID
}

type DetachOrDeleteVolumeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DetachOrDeleteVolumeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DetachOrDeleteVolumeResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *DetachOrDeleteVolumeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DetachOrDeleteVolumeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
