// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Affinity struct {
	LTarget *string `json:"LTarget,omitempty"`
	Operand *string `json:"Operand,omitempty"`
	RTarget *string `json:"RTarget,omitempty"`
	Weight  *int64  `json:"Weight,omitempty"`
}
