// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AllocStopResponse struct {
	EvalID *string `json:"EvalID,omitempty"`
	Index  *int64  `json:"Index,omitempty"`
}
