// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConsulIngressConfigEntry struct {
	Listeners []ConsulIngressListener `json:"Listeners,omitempty"`
	TLS       *ConsulGatewayTLSConfig `json:"TLS,omitempty"`
}
