// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConsulGatewayBindAddress struct {
	Address *string `json:"Address,omitempty"`
	Name    *string `json:"Name,omitempty"`
	Port    *int64  `json:"Port,omitempty"`
}
