// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConsulIngressService struct {
	Hosts []string `json:"Hosts,omitempty"`
	Name  *string  `json:"Name,omitempty"`
}

func (o *ConsulIngressService) GetHosts() []string {
	if o == nil {
		return nil
	}
	return o.Hosts
}

func (o *ConsulIngressService) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
