// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CSITopologyRequest struct {
	Preferred []CSITopology `json:"Preferred,omitempty"`
	Required  []CSITopology `json:"Required,omitempty"`
}
