// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeploymentPromoteRequest struct {
	All          *bool    `json:"All,omitempty"`
	DeploymentID *string  `json:"DeploymentID,omitempty"`
	Groups       []string `json:"Groups,omitempty"`
	Namespace    *string  `json:"Namespace,omitempty"`
	Region       *string  `json:"Region,omitempty"`
	SecretID     *string  `json:"SecretID,omitempty"`
}
