// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeploymentPauseRequest struct {
	DeploymentID *string `json:"DeploymentID,omitempty"`
	Namespace    *string `json:"Namespace,omitempty"`
	Pause        *bool   `json:"Pause,omitempty"`
	Region       *string `json:"Region,omitempty"`
	SecretID     *string `json:"SecretID,omitempty"`
}

func (o *DeploymentPauseRequest) GetDeploymentID() *string {
	if o == nil {
		return nil
	}
	return o.DeploymentID
}

func (o *DeploymentPauseRequest) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *DeploymentPauseRequest) GetPause() *bool {
	if o == nil {
		return nil
	}
	return o.Pause
}

func (o *DeploymentPauseRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *DeploymentPauseRequest) GetSecretID() *string {
	if o == nil {
		return nil
	}
	return o.SecretID
}
