// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeploymentPauseRequest struct {
	DeploymentID *string `json:"DeploymentID,omitempty"`
	Namespace    *string `json:"Namespace,omitempty"`
	Pause        *bool   `json:"Pause,omitempty"`
	Region       *string `json:"Region,omitempty"`
	SecretID     *string `json:"SecretID,omitempty"`
}
