// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DesiredUpdates struct {
	Canary            *int64 `json:"Canary,omitempty"`
	DestructiveUpdate *int64 `json:"DestructiveUpdate,omitempty"`
	Ignore            *int64 `json:"Ignore,omitempty"`
	InPlaceUpdate     *int64 `json:"InPlaceUpdate,omitempty"`
	Migrate           *int64 `json:"Migrate,omitempty"`
	Place             *int64 `json:"Place,omitempty"`
	Preemptions       *int64 `json:"Preemptions,omitempty"`
	Stop              *int64 `json:"Stop,omitempty"`
}
