// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DNSConfig struct {
	Options  []string `json:"Options,omitempty"`
	Searches []string `json:"Searches,omitempty"`
	Servers  []string `json:"Servers,omitempty"`
}

func (o *DNSConfig) GetOptions() []string {
	if o == nil {
		return nil
	}
	return o.Options
}

func (o *DNSConfig) GetSearches() []string {
	if o == nil {
		return nil
	}
	return o.Searches
}

func (o *DNSConfig) GetServers() []string {
	if o == nil {
		return nil
	}
	return o.Servers
}
