// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DrainSpec struct {
	Deadline         *int64 `json:"Deadline,omitempty"`
	IgnoreSystemJobs *bool  `json:"IgnoreSystemJobs,omitempty"`
}

func (o *DrainSpec) GetDeadline() *int64 {
	if o == nil {
		return nil
	}
	return o.Deadline
}

func (o *DrainSpec) GetIgnoreSystemJobs() *bool {
	if o == nil {
		return nil
	}
	return o.IgnoreSystemJobs
}
