// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EphemeralDisk struct {
	Migrate *bool  `json:"Migrate,omitempty"`
	SizeMB  *int64 `json:"SizeMB,omitempty"`
	Sticky  *bool  `json:"Sticky,omitempty"`
}

func (o *EphemeralDisk) GetMigrate() *bool {
	if o == nil {
		return nil
	}
	return o.Migrate
}

func (o *EphemeralDisk) GetSizeMB() *int64 {
	if o == nil {
		return nil
	}
	return o.SizeMB
}

func (o *EphemeralDisk) GetSticky() *bool {
	if o == nil {
		return nil
	}
	return o.Sticky
}
