// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FieldDiff struct {
	Annotations []string `json:"Annotations,omitempty"`
	Name        *string  `json:"Name,omitempty"`
	New         *string  `json:"New,omitempty"`
	Old         *string  `json:"Old,omitempty"`
	Type        *string  `json:"Type,omitempty"`
}
