// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FuzzySearchResponse struct {
	KnownLeader *bool                   `json:"KnownLeader,omitempty"`
	LastContact *int64                  `json:"LastContact,omitempty"`
	LastIndex   *int64                  `json:"LastIndex,omitempty"`
	Matches     map[string][]FuzzyMatch `json:"Matches,omitempty"`
	NextToken   *string                 `json:"NextToken,omitempty"`
	RequestTime *int64                  `json:"RequestTime,omitempty"`
	Truncations map[string]bool         `json:"Truncations,omitempty"`
}
