// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type HostNetworkInfo struct {
	Cidr          *string `json:"CIDR,omitempty"`
	Interface     *string `json:"Interface,omitempty"`
	Name          *string `json:"Name,omitempty"`
	ReservedPorts *string `json:"ReservedPorts,omitempty"`
}
