// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobEvaluateRequest struct {
	EvalOptions *EvalOptions `json:"EvalOptions,omitempty"`
	JobID       *string      `json:"JobID,omitempty"`
	Namespace   *string      `json:"Namespace,omitempty"`
	Region      *string      `json:"Region,omitempty"`
	SecretID    *string      `json:"SecretID,omitempty"`
}
