// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobRegisterRequest struct {
	EnforceIndex   *bool   `json:"EnforceIndex,omitempty"`
	EvalPriority   *int64  `json:"EvalPriority,omitempty"`
	Job            *Job    `json:"Job,omitempty"`
	JobModifyIndex *int64  `json:"JobModifyIndex,omitempty"`
	Namespace      *string `json:"Namespace,omitempty"`
	PolicyOverride *bool   `json:"PolicyOverride,omitempty"`
	PreserveCounts *bool   `json:"PreserveCounts,omitempty"`
	Region         *string `json:"Region,omitempty"`
	SecretID       *string `json:"SecretID,omitempty"`
}
