// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobRevertRequest struct {
	ConsulToken         *string `json:"ConsulToken,omitempty"`
	EnforcePriorVersion *int64  `json:"EnforcePriorVersion,omitempty"`
	JobID               *string `json:"JobID,omitempty"`
	JobVersion          *int64  `json:"JobVersion,omitempty"`
	Namespace           *string `json:"Namespace,omitempty"`
	Region              *string `json:"Region,omitempty"`
	SecretID            *string `json:"SecretID,omitempty"`
	VaultToken          *string `json:"VaultToken,omitempty"`
}
