// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobsParseRequest struct {
	Canonicalize *bool   `json:"Canonicalize,omitempty"`
	JobHCL       *string `json:"JobHCL,omitempty"`
	Hclv1        *bool   `json:"hclv1,omitempty"`
}

func (o *JobsParseRequest) GetCanonicalize() *bool {
	if o == nil {
		return nil
	}
	return o.Canonicalize
}

func (o *JobsParseRequest) GetJobHCL() *string {
	if o == nil {
		return nil
	}
	return o.JobHCL
}

func (o *JobsParseRequest) GetHclv1() *bool {
	if o == nil {
		return nil
	}
	return o.Hclv1
}
