// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobValidateResponse struct {
	DriverConfigValidated *bool    `json:"DriverConfigValidated,omitempty"`
	Error                 *string  `json:"Error,omitempty"`
	ValidationErrors      []string `json:"ValidationErrors,omitempty"`
	Warnings              *string  `json:"Warnings,omitempty"`
}
