// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MigrateStrategy struct {
	HealthCheck     *string `json:"HealthCheck,omitempty"`
	HealthyDeadline *int64  `json:"HealthyDeadline,omitempty"`
	MaxParallel     *int64  `json:"MaxParallel,omitempty"`
	MinHealthyTime  *int64  `json:"MinHealthyTime,omitempty"`
}
