// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MigrateStrategy struct {
	HealthCheck     *string `json:"HealthCheck,omitempty"`
	HealthyDeadline *int64  `json:"HealthyDeadline,omitempty"`
	MaxParallel     *int64  `json:"MaxParallel,omitempty"`
	MinHealthyTime  *int64  `json:"MinHealthyTime,omitempty"`
}

func (o *MigrateStrategy) GetHealthCheck() *string {
	if o == nil {
		return nil
	}
	return o.HealthCheck
}

func (o *MigrateStrategy) GetHealthyDeadline() *int64 {
	if o == nil {
		return nil
	}
	return o.HealthyDeadline
}

func (o *MigrateStrategy) GetMaxParallel() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxParallel
}

func (o *MigrateStrategy) GetMinHealthyTime() *int64 {
	if o == nil {
		return nil
	}
	return o.MinHealthyTime
}
