// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NamespaceCapabilities struct {
	DisabledTaskDrivers []string `json:"DisabledTaskDrivers,omitempty"`
	EnabledTaskDrivers  []string `json:"EnabledTaskDrivers,omitempty"`
}
