// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NodeCPUResources struct {
	CPUShares          *int64  `json:"CpuShares,omitempty"`
	ReservableCPUCores []int64 `json:"ReservableCpuCores,omitempty"`
	TotalCPUCores      *int64  `json:"TotalCpuCores,omitempty"`
}

func (o *NodeCPUResources) GetCPUShares() *int64 {
	if o == nil {
		return nil
	}
	return o.CPUShares
}

func (o *NodeCPUResources) GetReservableCPUCores() []int64 {
	if o == nil {
		return nil
	}
	return o.ReservableCPUCores
}

func (o *NodeCPUResources) GetTotalCPUCores() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCPUCores
}
