// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NodeUpdateDrainRequest struct {
	DrainSpec    *DrainSpec        `json:"DrainSpec,omitempty"`
	MarkEligible *bool             `json:"MarkEligible,omitempty"`
	Meta         map[string]string `json:"Meta,omitempty"`
	NodeID       *string           `json:"NodeID,omitempty"`
}
