// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NodeDiskResources struct {
	DiskMB *int64 `json:"DiskMB,omitempty"`
}

func (o *NodeDiskResources) GetDiskMB() *int64 {
	if o == nil {
		return nil
	}
	return o.DiskMB
}
