// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NodePurgeResponse struct {
	EvalCreateIndex *int64   `json:"EvalCreateIndex,omitempty"`
	EvalIDs         []string `json:"EvalIDs,omitempty"`
	NodeModifyIndex *int64   `json:"NodeModifyIndex,omitempty"`
}
