// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NodeReservedNetworkResources struct {
	ReservedHostPorts *string `json:"ReservedHostPorts,omitempty"`
}

func (o *NodeReservedNetworkResources) GetReservedHostPorts() *string {
	if o == nil {
		return nil
	}
	return o.ReservedHostPorts
}
