// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NodeDeviceResource struct {
	Attributes map[string]Attribute `json:"Attributes,omitempty"`
	Instances  []NodeDevice         `json:"Instances,omitempty"`
	Name       *string              `json:"Name,omitempty"`
	Type       *string              `json:"Type,omitempty"`
	Vendor     *string              `json:"Vendor,omitempty"`
}
