// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ObjectDiff struct {
	Fields  []FieldDiff  `json:"Fields,omitempty"`
	Name    *string      `json:"Name,omitempty"`
	Objects []ObjectDiff `json:"Objects,omitempty"`
	Type    *string      `json:"Type,omitempty"`
}

func (o *ObjectDiff) GetFields() []FieldDiff {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *ObjectDiff) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ObjectDiff) GetObjects() []ObjectDiff {
	if o == nil {
		return nil
	}
	return o.Objects
}

func (o *ObjectDiff) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

type ObjectDiffInput struct {
	Fields  []FieldDiff  `json:"Fields,omitempty"`
	Name    *string      `json:"Name,omitempty"`
	Objects []ObjectDiff `json:"Objects,omitempty"`
	Type    *string      `json:"Type,omitempty"`
}

func (o *ObjectDiffInput) GetFields() []FieldDiff {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *ObjectDiffInput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ObjectDiffInput) GetObjects() []ObjectDiff {
	if o == nil {
		return nil
	}
	return o.Objects
}

func (o *ObjectDiffInput) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
