// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PointValue struct {
	Name   *string   `json:"Name,omitempty"`
	Points []float32 `json:"Points,omitempty"`
}
