// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PreemptionConfig struct {
	BatchSchedulerEnabled    *bool `json:"BatchSchedulerEnabled,omitempty"`
	ServiceSchedulerEnabled  *bool `json:"ServiceSchedulerEnabled,omitempty"`
	SysBatchSchedulerEnabled *bool `json:"SysBatchSchedulerEnabled,omitempty"`
	SystemSchedulerEnabled   *bool `json:"SystemSchedulerEnabled,omitempty"`
}
