// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PreemptionConfig struct {
	BatchSchedulerEnabled    *bool `json:"BatchSchedulerEnabled,omitempty"`
	ServiceSchedulerEnabled  *bool `json:"ServiceSchedulerEnabled,omitempty"`
	SysBatchSchedulerEnabled *bool `json:"SysBatchSchedulerEnabled,omitempty"`
	SystemSchedulerEnabled   *bool `json:"SystemSchedulerEnabled,omitempty"`
}

func (o *PreemptionConfig) GetBatchSchedulerEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.BatchSchedulerEnabled
}

func (o *PreemptionConfig) GetServiceSchedulerEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.ServiceSchedulerEnabled
}

func (o *PreemptionConfig) GetSysBatchSchedulerEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.SysBatchSchedulerEnabled
}

func (o *PreemptionConfig) GetSystemSchedulerEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.SystemSchedulerEnabled
}
