// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RaftServer struct {
	Address      *string `json:"Address,omitempty"`
	ID           *string `json:"ID,omitempty"`
	Leader       *bool   `json:"Leader,omitempty"`
	Node         *string `json:"Node,omitempty"`
	RaftProtocol *string `json:"RaftProtocol,omitempty"`
	Voter        *bool   `json:"Voter,omitempty"`
}
