// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RescheduleEvent struct {
	PrevAllocID    *string `json:"PrevAllocID,omitempty"`
	PrevNodeID     *string `json:"PrevNodeID,omitempty"`
	RescheduleTime *int64  `json:"RescheduleTime,omitempty"`
}
