// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ScalingPolicyListStub struct {
	CreateIndex *int64            `json:"CreateIndex,omitempty"`
	Enabled     *bool             `json:"Enabled,omitempty"`
	ID          *string           `json:"ID,omitempty"`
	ModifyIndex *int64            `json:"ModifyIndex,omitempty"`
	Target      map[string]string `json:"Target,omitempty"`
	Type        *string           `json:"Type,omitempty"`
}

func (o *ScalingPolicyListStub) GetCreateIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.CreateIndex
}

func (o *ScalingPolicyListStub) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *ScalingPolicyListStub) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ScalingPolicyListStub) GetModifyIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.ModifyIndex
}

func (o *ScalingPolicyListStub) GetTarget() map[string]string {
	if o == nil {
		return nil
	}
	return o.Target
}

func (o *ScalingPolicyListStub) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
