// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ScalingPolicy struct {
	CreateIndex *int64                 `json:"CreateIndex,omitempty"`
	Enabled     *bool                  `json:"Enabled,omitempty"`
	ID          *string                `json:"ID,omitempty"`
	Max         *int64                 `json:"Max,omitempty"`
	Min         *int64                 `json:"Min,omitempty"`
	ModifyIndex *int64                 `json:"ModifyIndex,omitempty"`
	Namespace   *string                `json:"Namespace,omitempty"`
	Policy      map[string]interface{} `json:"Policy,omitempty"`
	Target      map[string]string      `json:"Target,omitempty"`
	Type        *string                `json:"Type,omitempty"`
}
