// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Service struct {
	Address           *string           `json:"Address,omitempty"`
	AddressMode       *string           `json:"AddressMode,omitempty"`
	CanaryMeta        map[string]string `json:"CanaryMeta,omitempty"`
	CanaryTags        []string          `json:"CanaryTags,omitempty"`
	CheckRestart      *CheckRestart     `json:"CheckRestart,omitempty"`
	Checks            []ServiceCheck    `json:"Checks,omitempty"`
	Connect           *ConsulConnect    `json:"Connect,omitempty"`
	EnableTagOverride *bool             `json:"EnableTagOverride,omitempty"`
	Meta              map[string]string `json:"Meta,omitempty"`
	Name              *string           `json:"Name,omitempty"`
	OnUpdate          *string           `json:"OnUpdate,omitempty"`
	PortLabel         *string           `json:"PortLabel,omitempty"`
	Provider          *string           `json:"Provider,omitempty"`
	TaggedAddresses   map[string]string `json:"TaggedAddresses,omitempty"`
	Tags              []string          `json:"Tags,omitempty"`
	TaskName          *string           `json:"TaskName,omitempty"`
}
