// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ServerHealth struct {
	Address     *string    `json:"Address,omitempty"`
	Healthy     *bool      `json:"Healthy,omitempty"`
	ID          *string    `json:"ID,omitempty"`
	LastContact *int64     `json:"LastContact,omitempty"`
	LastIndex   *int64     `json:"LastIndex,omitempty"`
	LastTerm    *int64     `json:"LastTerm,omitempty"`
	Leader      *bool      `json:"Leader,omitempty"`
	Name        *string    `json:"Name,omitempty"`
	SerfStatus  *string    `json:"SerfStatus,omitempty"`
	StableSince *time.Time `json:"StableSince,omitempty"`
	Version     *string    `json:"Version,omitempty"`
	Voter       *bool      `json:"Voter,omitempty"`
}
