// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TaskArtifact struct {
	GetterHeaders map[string]string `json:"GetterHeaders,omitempty"`
	GetterMode    *string           `json:"GetterMode,omitempty"`
	GetterOptions map[string]string `json:"GetterOptions,omitempty"`
	GetterSource  *string           `json:"GetterSource,omitempty"`
	RelativeDest  *string           `json:"RelativeDest,omitempty"`
}
