// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TaskGroup struct {
	Affinities                []Affinity               `json:"Affinities,omitempty"`
	Constraints               []Constraint             `json:"Constraints,omitempty"`
	Consul                    *Consul                  `json:"Consul,omitempty"`
	Count                     *int64                   `json:"Count,omitempty"`
	EphemeralDisk             *EphemeralDisk           `json:"EphemeralDisk,omitempty"`
	MaxClientDisconnect       *int64                   `json:"MaxClientDisconnect,omitempty"`
	Meta                      map[string]string        `json:"Meta,omitempty"`
	Migrate                   *MigrateStrategy         `json:"Migrate,omitempty"`
	Name                      *string                  `json:"Name,omitempty"`
	Networks                  []NetworkResource        `json:"Networks,omitempty"`
	ReschedulePolicy          *ReschedulePolicy        `json:"ReschedulePolicy,omitempty"`
	RestartPolicy             *RestartPolicy           `json:"RestartPolicy,omitempty"`
	Scaling                   *ScalingPolicy           `json:"Scaling,omitempty"`
	Services                  []Service                `json:"Services,omitempty"`
	ShutdownDelay             *int64                   `json:"ShutdownDelay,omitempty"`
	Spreads                   []Spread                 `json:"Spreads,omitempty"`
	StopAfterClientDisconnect *int64                   `json:"StopAfterClientDisconnect,omitempty"`
	Tasks                     []Task                   `json:"Tasks,omitempty"`
	Update                    *UpdateStrategy          `json:"Update,omitempty"`
	Volumes                   map[string]VolumeRequest `json:"Volumes,omitempty"`
}
