// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TaskCSIPluginConfig struct {
	HealthTimeout       *int64  `json:"HealthTimeout,omitempty"`
	ID                  *string `json:"ID,omitempty"`
	MountDir            *string `json:"MountDir,omitempty"`
	StagePublishBaseDir *string `json:"StagePublishBaseDir,omitempty"`
	Type                *string `json:"Type,omitempty"`
}
