// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Variable struct {
	CreateIndex *int64            `json:"CreateIndex,omitempty"`
	CreateTime  *int64            `json:"CreateTime,omitempty"`
	Items       map[string]string `json:"Items,omitempty"`
	ModifyIndex *int64            `json:"ModifyIndex,omitempty"`
	ModifyTime  *int64            `json:"ModifyTime,omitempty"`
	Namespace   *string           `json:"Namespace,omitempty"`
	Path        *string           `json:"Path,omitempty"`
}

func (o *Variable) GetCreateIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.CreateIndex
}

func (o *Variable) GetCreateTime() *int64 {
	if o == nil {
		return nil
	}
	return o.CreateTime
}

func (o *Variable) GetItems() map[string]string {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *Variable) GetModifyIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.ModifyIndex
}

func (o *Variable) GetModifyTime() *int64 {
	if o == nil {
		return nil
	}
	return o.ModifyTime
}

func (o *Variable) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *Variable) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}
