// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Variable struct {
	CreateIndex *int64            `json:"CreateIndex,omitempty"`
	CreateTime  *int64            `json:"CreateTime,omitempty"`
	Items       map[string]string `json:"Items,omitempty"`
	ModifyIndex *int64            `json:"ModifyIndex,omitempty"`
	ModifyTime  *int64            `json:"ModifyTime,omitempty"`
	Namespace   *string           `json:"Namespace,omitempty"`
	Path        *string           `json:"Path,omitempty"`
}
