// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConsulExposeConfig struct {
	Path []ConsulExposePath `json:"Path,omitempty"`
}

func (o *ConsulExposeConfig) GetPath() []ConsulExposePath {
	if o == nil {
		return nil
	}
	return o.Path
}
