// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/hashicorp/terraform-provider-nomad/v5/internal/sdk/internal/utils"
	"time"
)

type EvaluationStub struct {
	BlockedEval       *string    `json:"BlockedEval,omitempty"`
	CreateIndex       *int64     `json:"CreateIndex,omitempty"`
	CreateTime        *int64     `json:"CreateTime,omitempty"`
	DeploymentID      *string    `json:"DeploymentID,omitempty"`
	ID                *string    `json:"ID,omitempty"`
	JobID             *string    `json:"JobID,omitempty"`
	ModifyIndex       *int64     `json:"ModifyIndex,omitempty"`
	ModifyTime        *int64     `json:"ModifyTime,omitempty"`
	Namespace         *string    `json:"Namespace,omitempty"`
	NextEval          *string    `json:"NextEval,omitempty"`
	NodeID            *string    `json:"NodeID,omitempty"`
	PreviousEval      *string    `json:"PreviousEval,omitempty"`
	Priority          *int64     `json:"Priority,omitempty"`
	Status            *string    `json:"Status,omitempty"`
	StatusDescription *string    `json:"StatusDescription,omitempty"`
	TriggeredBy       *string    `json:"TriggeredBy,omitempty"`
	Type              *string    `json:"Type,omitempty"`
	WaitUntil         *time.Time `json:"WaitUntil,omitempty"`
}

func (e EvaluationStub) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluationStub) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *EvaluationStub) GetBlockedEval() *string {
	if o == nil {
		return nil
	}
	return o.BlockedEval
}

func (o *EvaluationStub) GetCreateIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.CreateIndex
}

func (o *EvaluationStub) GetCreateTime() *int64 {
	if o == nil {
		return nil
	}
	return o.CreateTime
}

func (o *EvaluationStub) GetDeploymentID() *string {
	if o == nil {
		return nil
	}
	return o.DeploymentID
}

func (o *EvaluationStub) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *EvaluationStub) GetJobID() *string {
	if o == nil {
		return nil
	}
	return o.JobID
}

func (o *EvaluationStub) GetModifyIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.ModifyIndex
}

func (o *EvaluationStub) GetModifyTime() *int64 {
	if o == nil {
		return nil
	}
	return o.ModifyTime
}

func (o *EvaluationStub) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *EvaluationStub) GetNextEval() *string {
	if o == nil {
		return nil
	}
	return o.NextEval
}

func (o *EvaluationStub) GetNodeID() *string {
	if o == nil {
		return nil
	}
	return o.NodeID
}

func (o *EvaluationStub) GetPreviousEval() *string {
	if o == nil {
		return nil
	}
	return o.PreviousEval
}

func (o *EvaluationStub) GetPriority() *int64 {
	if o == nil {
		return nil
	}
	return o.Priority
}

func (o *EvaluationStub) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *EvaluationStub) GetStatusDescription() *string {
	if o == nil {
		return nil
	}
	return o.StatusDescription
}

func (o *EvaluationStub) GetTriggeredBy() *string {
	if o == nil {
		return nil
	}
	return o.TriggeredBy
}

func (o *EvaluationStub) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *EvaluationStub) GetWaitUntil() *time.Time {
	if o == nil {
		return nil
	}
	return o.WaitUntil
}
