// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"nomad/internal/sdk/pkg/models/shared"
)

type DeleteJobSecurity struct {
	XNomadToken string `security:"scheme,type=apiKey,subtype=header,name=X-Nomad-Token"`
}

type DeleteJobRequest struct {
	// A Nomad ACL token.
	XNomadToken *string `header:"style=simple,explode=false,name=X-Nomad-Token"`
	// Boolean flag indicating whether the operation should apply to all instances of the job globally.
	Global *bool `queryParam:"style=form,explode=true,name=global"`
	// Can be used to ensure operations are only run once.
	IdempotencyToken *string `queryParam:"style=form,explode=true,name=idempotency_token"`
	// The job identifier.
	JobName string `pathParam:"style=simple,explode=false,name=jobName"`
	// Filters results based on the specified namespace.
	Namespace *string `queryParam:"style=form,explode=true,name=namespace"`
	// Boolean flag indicating whether to purge allocations of the job after deleting.
	Purge *bool `queryParam:"style=form,explode=true,name=purge"`
	// Filters results based on the specified region.
	Region *string `queryParam:"style=form,explode=true,name=region"`
}

type DeleteJobResponse struct {
	ContentType           string
	Headers               map[string][]string
	JobDeregisterResponse *shared.JobDeregisterResponse
	StatusCode            int
	RawResponse           *http.Response
}
