// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"nomad/internal/sdk/pkg/models/shared"
)

type GetMetricsSummaryRequest struct {
	// The format the user requested for the metrics summary (e.g. prometheus)
	Format *string `queryParam:"style=form,explode=true,name=format"`
}

type GetMetricsSummaryResponse struct {
	ContentType    string
	MetricsSummary *shared.MetricsSummary
	StatusCode     int
	RawResponse    *http.Response
}
