// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/hashicorp/terraform-provider-nomad/v2/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostDeploymentPauseSecurity struct {
	XNomadToken string `security:"scheme,type=apiKey,subtype=header,name=X-Nomad-Token"`
}

func (o *PostDeploymentPauseSecurity) GetXNomadToken() string {
	if o == nil {
		return ""
	}
	return o.XNomadToken
}

type PostDeploymentPauseRequest struct {
	DeploymentPauseRequest shared.DeploymentPauseRequest `request:"mediaType=application/json"`
	// A Nomad ACL token.
	XNomadToken *string `header:"style=simple,explode=false,name=X-Nomad-Token"`
	// Deployment ID.
	DeploymentID string `pathParam:"style=simple,explode=false,name=deploymentID"`
	// Can be used to ensure operations are only run once.
	IdempotencyToken *string `queryParam:"style=form,explode=true,name=idempotency_token"`
	// Filters results based on the specified namespace.
	Namespace *string `queryParam:"style=form,explode=true,name=namespace"`
	// Filters results based on the specified region.
	Region *string `queryParam:"style=form,explode=true,name=region"`
}

func (o *PostDeploymentPauseRequest) GetDeploymentPauseRequest() shared.DeploymentPauseRequest {
	if o == nil {
		return shared.DeploymentPauseRequest{}
	}
	return o.DeploymentPauseRequest
}

func (o *PostDeploymentPauseRequest) GetXNomadToken() *string {
	if o == nil {
		return nil
	}
	return o.XNomadToken
}

func (o *PostDeploymentPauseRequest) GetDeploymentID() string {
	if o == nil {
		return ""
	}
	return o.DeploymentID
}

func (o *PostDeploymentPauseRequest) GetIdempotencyToken() *string {
	if o == nil {
		return nil
	}
	return o.IdempotencyToken
}

func (o *PostDeploymentPauseRequest) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *PostDeploymentPauseRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

type PostDeploymentPauseResponse struct {
	// HTTP response content type for this operation
	ContentType              string
	DeploymentUpdateResponse *shared.DeploymentUpdateResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostDeploymentPauseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostDeploymentPauseResponse) GetDeploymentUpdateResponse() *shared.DeploymentUpdateResponse {
	if o == nil {
		return nil
	}
	return o.DeploymentUpdateResponse
}

func (o *PostDeploymentPauseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostDeploymentPauseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
