// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/hashicorp/terraform-provider-nomad/v5/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostAllocationStopSecurity struct {
	XNomadToken string `security:"scheme,type=apiKey,subtype=header,name=X-Nomad-Token"`
}

func (o *PostAllocationStopSecurity) GetXNomadToken() string {
	if o == nil {
		return ""
	}
	return o.XNomadToken
}

type PostAllocationStopRequest struct {
	// A Nomad ACL token.
	XNomadToken *string `header:"style=simple,explode=false,name=X-Nomad-Token"`
	// Allocation ID.
	AllocID string `pathParam:"style=simple,explode=false,name=allocID"`
	// If set, wait until query exceeds given index. Must be provided with WaitParam.
	Index *int64 `header:"style=simple,explode=false,name=index"`
	// Filters results based on the specified namespace.
	Namespace *string `queryParam:"style=form,explode=true,name=namespace"`
	// Indicates where to start paging for queries that support pagination.
	NextToken *string `queryParam:"style=form,explode=true,name=next_token"`
	// Flag indicating whether to delay shutdown when requesting an allocation stop.
	NoShutdownDelay *bool `queryParam:"style=form,explode=true,name=no_shutdown_delay"`
	// Maximum number of results to return.
	PerPage *int64 `queryParam:"style=form,explode=true,name=per_page"`
	// Constrains results to jobs that start with the defined prefix
	Prefix *string `queryParam:"style=form,explode=true,name=prefix"`
	// Filters results based on the specified region.
	Region *string `queryParam:"style=form,explode=true,name=region"`
	// If present, results will include stale reads.
	Stale *string `queryParam:"style=form,explode=true,name=stale"`
	// Provided with IndexParam to wait for change.
	Wait *string `queryParam:"style=form,explode=true,name=wait"`
}

func (o *PostAllocationStopRequest) GetXNomadToken() *string {
	if o == nil {
		return nil
	}
	return o.XNomadToken
}

func (o *PostAllocationStopRequest) GetAllocID() string {
	if o == nil {
		return ""
	}
	return o.AllocID
}

func (o *PostAllocationStopRequest) GetIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.Index
}

func (o *PostAllocationStopRequest) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *PostAllocationStopRequest) GetNextToken() *string {
	if o == nil {
		return nil
	}
	return o.NextToken
}

func (o *PostAllocationStopRequest) GetNoShutdownDelay() *bool {
	if o == nil {
		return nil
	}
	return o.NoShutdownDelay
}

func (o *PostAllocationStopRequest) GetPerPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *PostAllocationStopRequest) GetPrefix() *string {
	if o == nil {
		return nil
	}
	return o.Prefix
}

func (o *PostAllocationStopRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *PostAllocationStopRequest) GetStale() *string {
	if o == nil {
		return nil
	}
	return o.Stale
}

func (o *PostAllocationStopRequest) GetWait() *string {
	if o == nil {
		return nil
	}
	return o.Wait
}

type PostAllocationStopResponse struct {
	AllocStopResponse *shared.AllocStopResponse
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostAllocationStopResponse) GetAllocStopResponse() *shared.AllocStopResponse {
	if o == nil {
		return nil
	}
	return o.AllocStopResponse
}

func (o *PostAllocationStopResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAllocationStopResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *PostAllocationStopResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAllocationStopResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
